[pytest]
filterwarnings =
    ignore:datetime\.datetime\.utcfromtimestamp\(\) is deprecated:DeprecationWarning:dateutil\.tz\.tz
    ignore:datetime\.datetime\.utcnow\(\) is deprecated:DeprecationWarning:flask_login\.login_manager
